services:
  api:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
      - "8888:8888"
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_ENCRYPTION_SECRET: ${APP_ENCRYPTION_SECRET}
      APP_ALLOWED_ORIGINS: ${APP_ALLOWED_ORIGINS}
      GMAIL_OAUTH_CLIENT_ID: ${GMAIL_OAUTH_CLIENT_ID}
      GMAIL_OAUTH_CLIENT_SECRET: ${GMAIL_OAUTH_CLIENT_SECRET}
    networks:
      - network
    volumes:
      - ./tokens:/app/tokens
      - ./logs:/app/logs
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - rest-email-bridge-db-data:/var/lib/postgresql/data
      - ./infrastructure/src/main/resources/db-scripts:/docker-entrypoint-initdb.d
    networks:
      - network

volumes:
  rest-email-bridge-db-data:

networks:
  network:
    driver: bridge