create table mail
(
    id                bigint generated by default as identity primary key,
    body              varchar(7000) not null,
    recipient         varchar(200) not null,
    sender            varchar(200) not null,
    subjet            varchar(150) not null,
    created_at        timestamp,
    status            varchar
        constraint check_status
            check (((status)::text = 'PENDING'::text) OR ((status)::text = 'SENT'::text) OR
                   ((status)::text = 'FAILED'::text)),
    error_description varchar(10000),
    constraint check_error_description
        check ((((status)::text = 'FAILED'::text) AND
                ((error_description IS NOT NULL) OR ((error_description)::text <> ''::text))) OR
               (((status)::text <> 'FAILED'::text) AND (error_description IS NULL)))
);